improve globalmem examples

diff --git a/code/06/包含2个globalmem设备的驱动/Makefile b/code/06/包含2个globalmem设备的驱动/Makefile
--- a/code/06/包含2个globalmem设备的驱动/Makefile
+++ b/code/06/包含2个globalmem设备的驱动/Makefile
@@ -18,21 +18,29 @@ ROOT=..
 #include $(ROOT)/Make.defines.$(PLATFORM)
 
 MODULE_NAME := globalmem_two
+DEVICE_BASENAME := gatieme
+DEVICE_COUNT := 2
+IOCTL_TEST_BIN := globalmem_ioctl_test
+IOCTL_TEST_SRC := globalmem_ioctl_test.c
 
 ifneq ($(KERNELRELEASE),)
 
 #CFG_FLAGS += -O2  -I./
 #EXTRA_CFLAGS  += $(C_FLAGS) $(CFG_INC) $(CFG_INC)
 
-
-
 obj-m := $(MODULE_NAME).o #globalmem.o
 
 else
 
 KERNELDIR ?= /lib/modules/$(shell uname -r)/build
-
 PWD := $(shell pwd)
+CC ?= gcc
+CFLAGS ?= -Wall -Wextra -O2
+
+ioctl_test: $(IOCTL_TEST_BIN)
+
+$(IOCTL_TEST_BIN): $(IOCTL_TEST_SRC) globalmem_ioctl.h
+	$(CC) $(CFLAGS) -I. -o $@ $(IOCTL_TEST_SRC)
 
 modules:
 	make -C $(KERNELDIR) M=$(PWD) modules
@@ -42,32 +50,49 @@ modules_install:
 
 
 
-insmod:
-	sudo insmod $(MODULE_NAME).ko
-	sudo mknod /dev/gatieme c 300 0
-	sudo chmod 777 /dev/gatieme
+insmod: modules
+	sudo insmod $(MODULE_NAME).ko globalmem_major=0
+	major=$$(awk '$$2 == "globalmem" {print $$1}' /proc/devices); \
+	if [ -z "$$major" ]; then \
+		echo "failed to find globalmem major in /proc/devices"; \
+		exit 1; \
+	fi; \
+	for minor in $$(seq 0 $$(($(DEVICE_COUNT) - 1))); do \
+		node=/dev/$(DEVICE_BASENAME)$$minor; \
+		sudo rm -f $$node; \
+		sudo mknod $$node c $$major $$minor; \
+		sudo chmod 666 $$node; \
+	done
+
 reinsmod:
-	sudo rmmod $(MODULE_NAME)
-	sudo insmod $(MODULE_NAME).ko
+	-$(MAKE) rmmod
+	$(MAKE) insmod
 
 github:
 	cd $(ROOT) && make github
 
 rmmod:
-	sudo rmmod $(MODULE_NAME)
-	sudo rm /dev/gatieme 
+	-sudo rmmod $(MODULE_NAME)
+	for minor in $$(seq 0 $$(($(DEVICE_COUNT) - 1))); do \
+		sudo rm -f /dev/$(DEVICE_BASENAME)$$minor; \
+	done
 
 test :
 	sudo ../injector/memInjector -l stack -m random -t word_0 --time 1 --timeout 3 -p 1
 
+test_ioctl: ioctl_test
+	@if [ ! -e /dev/$(DEVICE_BASENAME)0 ]; then \
+		echo "/dev/$(DEVICE_BASENAME)0 not found; run 'make insmod' first."; \
+		exit 1; \
+	fi
+	sudo ./$(IOCTL_TEST_BIN) /dev/$(DEVICE_BASENAME)0
+
 clean:
 	make -C $(KERNELDIR) M=$(PWD) clean
-	rm -f modules.order Module.symvers Module.markers
+	rm -f modules.order Module.symvers Module.markers $(IOCTL_TEST_BIN)
 
-.PHNOY:
-	modules modules_install clean
+.PHONY: modules modules_install insmod reinsmod rmmod test ioctl_test test_ioctl clean github
 
 
 
 endif
-
